name: Build CloudDevOps Image

on:
  push:
    branches: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
      run: |
        docker buildx build \
          --tag cloudops-guru/multiarch-example:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
